# Generated by Django 2.1.2 on 2018-10-08 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buscoayuda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajador',
            name='imagen',
        ),
    ]
